### ISSUE TITLE
kedro airflow plugins: ValueError Pipeline input(s) not found in the DataCatalog

### ISSUE THREAD

**Issue by allenhaozi** [kedro-org/kedro-plugins#61]
## Description

using the kedro-airflow plugin generate airflow dag

but I got the following error

```
Traceback (most recent call last):
  File "/Users/mahao/airflow/dags/pandas_iris_01_dag.py", line 38, in execute
    session.run(self.pipeline_name, node_names=[self.node_name])
  File "/Users/mahao/miniconda3/envs/airflow/lib/python3.8/site-packages/kedro/framework/session/session.py", line 391, in run
    run_result = runner.run(
  File "/Users/mahao/miniconda3/envs/airflow/lib/python3.8/site-packages/kedro/runner/runner.py", line 74, in run
    raise ValueError(
ValueError: Pipeline input(s) {'X_test', 'y_train', 'X_train'} not found in the DataCatalog
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:
```
kedro, version 0.18.1
```
```
Name: kedro-airflow
Version: 0.5.0
Summary: Kedro-Airflow makes it easy to deploy Kedro projects to Airflow
Home-page: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-airflow
Author: Kedro
Author-email: 
License: Apache Software License (Apache 2.0)
Location: /Users/mahao/miniconda3/envs/airflow/lib/python3.8/site-packages
Requires: kedro, python-slugify, semver
Required-by: 
```
```
Python 3.8.13

```

**Comment by noklam** [comment]
@allenhaozi Did you get this error while generating the DAGs? It would be great if you can describe the necessary steps to reproduce the error you get.

**Comment by merelcht** [comment]
Hi @allenhaozi, do you still need help resolving this problem?

**Comment by allenhaozi** [comment]
> Hi @allenhaozi, do you still need help resolving this problem?

I know why now. The reason is how I used it.
