### ISSUE TITLE
Kedro-Datasets PyPI source distribution Tar.gz does not include requirements.txt

### ISSUE THREAD

**Issue by rxm7706** [kedro-org/kedro-plugins#86]
## Description
PyPi  Source Distribution ; does not include requirements.txt, test_requirements.txt and lincense.md

https://files.pythonhosted.org/packages/0f/8e/1ca7d83226970935d2eeb94611dea4be3eb888b2ea9393f343eabd2560b0/kedro-datasets-0.0.6.tar.gz

https://pypi.org/project/kedro-datasets/#files

## Context
setup.py refers to requirements.txt and test_requirements.txt -
license is needed for distribution through conda and is ideally included in source. 

## Expected Result
Source Distribution should contain license, and files needed to run setup.py
Source Distribution should be similar to Kedro-Airflow and eventually could be made available as a conda installer. 

## Actual Result

Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.3
* Kedro plugin and kedro plugin version used (`pip show kedro-airflow`): kedro-datasets
* Python version used (`python -V`): 3.7.12
* Operating system and version: Linux

**Comment by merelcht** [comment]
Should probably be addressed as part of https://github.com/kedro-org/kedro/issues/2334

**Comment by astrojuanlu** [comment]
Indeed, this can be reproduced locally in current `main`:

```
python -m build                                                          (kedro38-dev) 
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Getting build dependencies for sdist...
running egg_info
...
Creating tar archive
removing 'kedro-datasets-1.2.0' (and everything under it)
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Getting build dependencies for wheel...
Traceback (most recent call last):
  File "/Users/juan_cano/.micromamba/envs/kedro38-dev/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/Users/juan_cano/.micromamba/envs/kedro38-dev/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/juan_cano/.micromamba/envs/kedro38-dev/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/private/var/folders/r7/ywj0_kvj0mxfkdkx0jrgh73r0000gn/T/build-env-2rmsc8uw/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/private/var/folders/r7/ywj0_kvj0mxfkdkx0jrgh73r0000gn/T/build-env-2rmsc8uw/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
    self.run_setup()
  File "/private/var/folders/r7/ywj0_kvj0mxfkdkx0jrgh73r0000gn/T/build-env-2rmsc8uw/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/private/var/folders/r7/ywj0_kvj0mxfkdkx0jrgh73r0000gn/T/build-env-2rmsc8uw/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 18, in <module>
  File "/Users/juan_cano/.micromamba/envs/kedro38-dev/lib/python3.8/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```
